---
- name: Create a adguard-home directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ adguard_home_user }}/adguard-home/"
    state: directory

# - name: Create a workdir directory if it does not exist
#   ansible.builtin.file:
#     path: "/home/{{ adguard_home_user }}/adguard-home/workdir/"
#     state: directory

# - name: Create a confdir directory if it does not exist
#   ansible.builtin.file:
#     path: "/home/{{ adguard_home_user }}/adguard-home/confdir/"
#     state: directory

- name: pull adguardhome docker image
  community.docker.docker_image:
    name: adguard/adguardhome
    source: pull
    tag: latest
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: arm64

- name: Template docker-compose file to adguard-home folder
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/home/{{ adguard_home_user }}/adguard-home/docker-compose.yml"
    owner: "{{ adguard_home_user }}"
    group: "{{ adguard_home_user }}"
    mode: '755'
