---
odroid_iancleary_user_password: "{{ vault_odroid_iancleary_user_password }}"
odroid_nextcloud_pgsql_password: "{{ vault_odroid_nextcloud_pgsql_password }}"
odroid_nixos_modules:
  - nextcloud.nix
  - docker.nix
  - tailscale.nix
  - homeassistant.nix
  - unifi.nix

odroid_container_user: "iancleary"
odroid_container_user_group: "users"

data_pool: "dpool"

# https://github.com/advplyr/audiobookshelf/pkgs/container/audiobookshelf
audiobookshelf_docker_image: "ghcr.io/advplyr/audiobookshelf"
audiobookshelf_docker_version: "2.17.6"

homeassistant_mosquitto_user: "{{ vault_homeassistant_mosquitto_user }}"
homeassistant_mosquitto_password: "{{ vault_homeassistant_mosquitto_password }}"

iancleary_tailscale_auth_key: "{{ vault_iancleary_tailscale_auth_key }}"
