---
odroid_iancleary_user_password: "{{ vault_odroid_iancleary_user_password }}"
odroid_nextcloud_pgsql_password: "{{ vault_odroid_nextcloud_pgsql_password }}"
odroid_nixos_modules:
  - nextcloud.nix
  - docker.nix
  - tailscale.nix
  - homeassistant.nix
  - unifi.nix

odroid_container_user: iancleary
odroid_container_user_group: users

data_pool: dpool

# https://github.com/advplyr/audiobookshelf/pkgs/container/audiobookshelf
audiobookshelf_docker_image: ghcr.io/advplyr/audiobookshelf
audiobookshelf_docker_version: 2.15.1

homeassistant_mosquitto_user: "{{ vault_homeassistant_mosquitto_user }}"
homeassistant_mosquitto_password: "{{ vault_homeassistant_mosquitto_password }}"

# MongoDB for Unifi, supports 3.6 through 4.4 as of 2024-02-21
# Starting with version 8.1 of Unifi Network Application, mongodb 3.6 through 7.0 are supported.
# https://github.com/linuxserver/docker-unifi-network-application?tab=readme-ov-file#setting-up-your-external-database
unifi_mongo_version: 4.4
unifi_mongo_password: "{{ vault_unifi_mongo_password }}"
unifi_network_version: "8.3.32-ls57"

iancleary_tailscale_auth_key: "{{ vault_iancleary_tailscale_auth_key }}"
