---
- name: Perform a safe-upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: Reboot the server (if required)
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true

- name: Remove dependencies that are no longer reboot_required_file.stat.exists
  ansible.builtin.apt:
    autoremove: yes
    