---
- name: pull lscr.io/linuxserver/unifi-controller docker image
  community.docker.docker_image:
    name: lscr.io/linuxserver/unifi-controller
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Template docker-compose file to unifi-controller folder
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/home/{{ unifi_controller_user }}/unifi-controller/docker-compose.yml"
    owner: "{{ unifi_controller_user }}"
    group: "{{ unifi_controller_user }}"

- name: Create and start services
  community.docker.docker_compose:
    project_src: "/home/{{ unifi_controller_user }}/unifi-controller/"
    state: "{{ unifi_controller_state }}"
