---
- name: Run docker-compose.yml down
  ansible.builtin.command: docker-compose down
  args:
    chdir: /opt/mailserver/

# - name: Get Email List
#   ansible.builtin.command: ./setup.sh email list
#   args:
#     chdir: /opt/mailserver/
#   register: raw_email_list

# - name: Debug Email List
#   ansible.builtin.debug:
#     var: raw_email_list

# - name: Debug Email List
#   ansible.builtin.debug:
#     var: item
#   with_items: "{{ raw_email_list.stdout_lines }}"

# - set_fact:
#    email_list: "{{ raw_email_list.stdout_lines|select()|list }}"

# - name: Debug Email List
#   ansible.builtin.debug:
#     var: email_list

# - name: Debug Email List Items
#   ansible.builtin.debug:
#     var: "{{ item.replace('* ','') }}"
#   with_items: "{{ email_list }}"

- name: Add email accounts
  ansible.builtin.command: ./setup.sh email add {{ item.email }} {{ item.password }}
  args:
    chdir: /opt/mailserver/
  with_items: "{{ docker_mailserver_email_accounts }}"