---
- name: Pull tailscale image
  community.docker.docker_image:
    name: docker.io/tailscale/tailscale
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Pull audiobookshelf image
  community.docker.docker_image:
    name: "{{ audiobookshelf_docker_image }}"
    source: pull
    tag: "{{ audiobookshelf_docker_version }}"
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Create the directories that the compose file uses
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/{{ data_pool }}/audiobookshelf/tailscale-state/"
    - "/{{ data_pool }}/audiobookshelf/tailscale-config/"
    - "/{{ data_pool }}/audiobookshelf/tailscale-config/config/"
    - "/{{ data_pool }}/audiobookshelf/Audiobooks/"
    - "/{{ data_pool }}/audiobookshelf/Podcasts/"
    - "/{{ data_pool }}/audiobookshelf/config/"
    - "/{{ data_pool }}/audiobookshelf/metadata/"

- name: Copy the docker compose file to the server
  ansible.builtin.template:
    src: "audiobookshelf-docker-compose.yml"
    dest: "/{{ data_pool }}/audiobookshelf/docker-compose.yml"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

# Make sure this dest file maps to /config/tailscale.json in the container...
# inspect manually if it is the first time placing this file onto your server
- name: Copy the tailscale json file to the server
  ansible.builtin.template:
    src: "tailscale.json"
    dest: "/{{ data_pool }}/audiobookshelf/tailscale-config/config/tailscale.json"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

- name: Stop services
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/audiobookshelf"
    state: stopped

- name: Pause for 3 seconds to allow services to fully stop
  ansible.builtin.pause:
    seconds: 3

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/audiobookshelf"
    state: present
