---
version: "3.7"
name: stirling-pdf
services:
  tailscale:
    hostname: pdfs # This will become the tailscale device name
    image: docker.io/tailscale/tailscale:latest
    environment:
      - TS_AUTH_KEY={{ iancleary_tailscale_auth_key }}
      - TS_SERVE_CONFIG=/config/tailscale.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/tailscale-state:/var/lib/tailscale
      - ${PWD}/tailscale-config/config:/config # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun" # Required for tailscale to work
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    restart: unless-stopped

  stirling-pdf:
    image: docker.io/frooodle/s-pdf:latest
    container_name: s-pdf
    network_mode: service:tailscale
    depends_on:
      - tailscale
    volumes:
      - ${PWD}/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ${PWD}/extraConfigs:/configs
    #      - ${PWD}/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped

volumes:
  stirling-pdf:
    driver: local
  tailscale:
    driver: local
