---
# - name: Ensure GitHub user accounts are present.
#   ansible.builtin.debug:
#     msg: "privilege escalation successful"

- name: Ensure GitHub user accounts are present.
  ansible.builtin.user:
    name: "{{ item.name | default(item) }}"
    shell: /bin/bash
    createhome: true
    groups: "{{ item.groups | default(omit) }}"
    append: "yes"
    home: /home/{{ item.name | default(item) }}
    password: "{{ item.password | default(omit) }}"
    state: present
  with_items: "{{ github_users }}"

- name: Ensure authorized_keys for GitHub user accounts are present.
  authorized_key:
    user: "{{ item.name | default(item) }}"
    key: "{{ github_url }}/{{ item.name | default(item) }}.keys"
    manage_dir: true
    exclusive: "{{ github_users_authorized_keys_exclusive }}"
  with_items: "{{ github_users }}"

- name: Ensure user accounts in github_users_absent are absent.
  ansible.builtin.user:
    name: "{{ item.name | default(item) }}"
    state: absent
  with_items: "{{ github_users_absent }}"