---
- name: Pull homeassistant image
  community.docker.docker_image:
    name: ghcr.io/home-assistant/home-assistant
    source: pull
    tag: stable
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Pull docker.io eclipse-mosquitto:2 image
  community.docker.docker_image:
    name: eclipse-mosquitto
    source: pull
    tag: 2
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Pull ghcr.io/tasmoadmin/tasmoadmin image
  community.docker.docker_image:
    name: ghcr.io/tasmoadmin/tasmoadmin
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Create the directories that the compose file uses
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/{{ data_pool }}/homeassistant/config/"
    - "/{{ data_pool }}/homeassistant/mosquitto/config/"
    - "/{{ data_pool }}/homeassistant/mosquitto/data/"
    - "/{{ data_pool }}/homeassistant/mosquitto/log/"
    - "/{{ data_pool }}/homeassistant/tasmoadmin/"

- name: Copy the docker compose file to the server
  ansible.builtin.template:
    src: "homeassistant-docker-compose.yml"
    dest: "/{{ data_pool }}/homeassistant/docker-compose.yml"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

# - name: Copy the mosquitto config file to the server
#   ansible.builtin.template:
#     src: "mosquitto.beforepassword.conf"
#     dest: "/{{ data_pool }}/homeassistant/mosquitto/config/mosquitto.conf"
#     owner: "{{ odroid_container_user }}"
#     group: "{{ odroid_container_user_group }}"
#     mode: "0644"

- name: Copy the mosquitto password file to the server
  ansible.builtin.template:
    src: "mosquitto.password.txt"
    dest: "/{{ data_pool }}/homeassistant/mosquitto/config/password.txt"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0660"

- name: Copy the mosquitto config (after password) file to the server
  ansible.builtin.template:
    src: "mosquitto.afterpassword.conf"
    dest: "/{{ data_pool }}/homeassistant/mosquitto/config/mosquitto.conf"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/homeassistant"
    state: present
  register: homeassistant_docker_compose

# https://mosquitto.org/man/mosquitto_passwd-1.html
# Warning: File /mosquitto/config/password.txt owner is not root.
# Future versions will refuse to load this file.To fix this,
# use `chown root /mosquitto/config/password.txt`.
# Warning: File /mosquitto/config/password.txt group is not root.
# Future versions will refuse to load this file.
- name: Chown the mosquitto password file
  ansible.builtin.shell: "docker compose exec mosquitto chown root:root /mosquitto/config/password.txt"
  args:
    chdir: "/{{ data_pool }}/homeassistant"

# template the mosquitto password file with ansible, then run the mosquitto_passwd command to hash the passwords
# - name: Upgrade the mosquitto password to use hashed passwords
#   ansible.builtin.shell: "docker compose exec mosquitto mosquitto_passwd -U /mosquitto/config/password.txt"
#   args:
#     chdir: "/{{ data_pool }}/homeassistant"

# template the mosquitto password file with ansible, then run the mosquitto_passwd command to hash the passwords
- name: Use mosquitto_passwd to set the homeassistant user and password
  ansible.builtin.shell: "docker compose exec mosquitto mosquitto_passwd -b /mosquitto/config/password.txt {{ homeassistant_mosquitto_user }} {{ homeassistant_mosquitto_password }}"
  args:
    chdir: "/{{ data_pool }}/homeassistant"

- name: Restart mosquitto service
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/homeassistant"
    state: restarted
    services:
      - mosquitto
  register: homeassistant_docker_compose

# disable anonymous access to the mosquitto broker, after hashing the passwords
# - name: Copy the mosquitto config (after password) file to the server
#   ansible.builtin.template:
#     src: "mosquitto.afterpassword.conf"
#     dest: "/{{ data_pool }}/homeassistant/mosquitto/config/mosquitto.conf"
#     owner: "{{ odroid_container_user }}"
#     group: "{{ odroid_container_user_group }}"
#     mode: "0644"
