---
- name: Tailscale Install Signing Key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Tailscale apt source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: Update repositories cache and install "tailscale" package
  ansible.builtin.apt:
    name: tailscale
    update_cache: yes

# login directly via ssh
# connect your machine to your Tailscale network and authenticate in your browser:

## sudo tailscale up

# You’re connected! You can find your Tailscale IPv4 address by running:

## tailscale ip -4
