---
- name: Tailscale Install Signing Key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower }}/{{ ansible_distribution_release|lower }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Tailscale apt source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main"
    state: present
  register: tailscale_new_install

- name: Update repositories cache, if needed
  ansible.builtin.apt:
    update_cache: yes
  when: tailscale_new_install.changed

- name: Install "tailscale" package
  ansible.builtin.apt:
    name: tailscale

# login directly via ssh
# connect your machine to your Tailscale network and authenticate in your browser:

## sudo tailscale up

# You’re connected! You can find your Tailscale IPv4 address by running:

## tailscale ip -4
