---
- name: Pull lscr.io/linuxserver/unifi-network-application image
  community.docker.docker_image:
    name: lscr.io/linuxserver/unifi-network-application
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Pull docker.io/mongo image
  community.docker.docker_image:
    name: docker.io/mongo
    source: pull
    tag: "{{ unifi_mongo_version }}"
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Create the directories that the compose file uses
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/{{ data_pool }}/unifi/config/"
    - "/{{ data_pool }}/unifi/mongo/"
    - "/{{ data_pool }}/unifi/mongo/data/"
    - "/{{ data_pool }}/unifi/mongo/init/"

- name: Copy the docker compose file to the server
  ansible.builtin.template:
    src: "unifi-docker-compose.yml"
    dest: "/{{ data_pool }}/unifi/docker-compose.yml"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

- name: Copy the mongo init-mongo.js file to the server
  ansible.builtin.template:
    src: "init-mongo.js"
    dest: "/{{ data_pool }}/unifi/mongo/init/init-mongo.js"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

- name: Stop services
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/unifi"
    state: stopped

- name: Pause for 3 seconds to allow services to fully stop
  ansible.builtin.pause:
    seconds: 3

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/unifi"
    state: present
  register: unifi_docker_compose
