# list recipes
help:
  just --list

now := `date +"%Y-%m-%d_%H.%M.%S"`
hostname := `uname -n`

# Install ansible-galaxy roles/collections
galaxy:
    uv run ansible-galaxy install -r requirements.yml

# Run ansible playbook_odroid.yml
odroid:
    uv run ansible-playbook playbook_odroid.yml --ask-vault-pass

# Run ansible playbook_tailscale.yml
tailscale:
    uv run ansible-playbook playbook_tailscale.yml --ask-vault-pass

# View ansible-vault
view:
    uv run ansible-vault view group_vars/all/vault.yml

# edit ansible-vault
edit:
    export EDITOR=nano && uv run ansible-vault edit group_vars/all/vault.yml
