---
- name: Configure Mail In A Box
  hosts: mail
  remote_user: root
  
  # vars_files:
  #   - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - {role: github-users, tags: ['ssh-keys']}
    

