---
- name: Configure Cloud 1 (root)
  hosts: cloud1
  remote_user: root
  
  # vars_files:
  #   - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - {role: github-users, tags: ['ssh-keys']}
    - {role: iancleary.docker, tags: ['docker']}
    # - {role: mailserver-provision, tags: ['mailserver-provision']}
    # - {role: mailserver-configure, tags: ['mailserver-configure']}
