---
- name: Update Odroid Server
  hosts: primary
  remote_user: iancleary
  roles:
    - {
        role: tailscale_key,
        become: true,
        tags: ["tailscale_key"],
        ansible_become_password: "{{ odroid_iancleary_user_password }}",
      }
    - {
        role: containers_audiobookshelf,
        become: true,
        tags: ["audiobookshelf"],
        ansible_become_password: "{{ odroid_iancleary_user_password }}",
      }
    - {
        role: containers_jellyfin,
        become: true,
        tags: ["jellyfin"],
        ansible_become_password: "{{ odroid_iancleary_user_password }}",
      }
    - {
        role: containers_s_pdf,
        become: true,
        tags: ["pdf"],
        ansible_become_password: "{{ odroid_iancleary_user_password }}",
      }
    - {
        role: containers_homeassistant,
        become: true,
        tags: ["homeassistant"],
        ansible_become_password: "{{ odroid_iancleary_user_password }}",
      }
