---
- name: Upgrade and reboot all Raspberry Pis
  hosts: raspberrypi3bv2p0
  remote_user: iancleary
  roles:
    - {role: upgrade, become: true, tags: ['upgrade'], ansible_become_password: "{{ iancleary_user_password }}"}