---
- name: Update tailscale_keys on odroid servers
  hosts: all
  remote_user: iancleary
  roles:
    - {
        role: tailscale_key,
        become: true,
        tags: ["tailscale_key"],
        ansible_become_password: "{{ odroid_iancleary_user_password }}",
      }

