---
- name: Create a etc-pihole directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ pi_hole_user }}/pi-hole/etc-pihole/"
    state: directory
    mode: '0755'

- name: Create a etc-dnsmasq.d directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ pi_hole_user }}/pi-hole/etc-dnsmasq.d/"
    state: directory
    mode: '0755'

- name: pull pihole/pihole docker image
  community.docker.docker_image:
    name: pihole/pihole
    source: pull
    tag: latest
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: arm64

- name: Template docker-compose file to pi-hole folder
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/home/{{ pi_hole_user }}/pi-hole/docker-compose.yml"
    owner: "{{ pi_hole_user }}"
    group: "{{ pi_hole_user }}"
    mode: '0755'