---
- name: Pull tailscale image
  community.docker.docker_image:
    name: docker.io/tailscale/tailscale:latest
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Pull jellyfin image
  community.docker.docker_image:
    name: docker.io/jellyfin/jellyfin
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Create the directories that the compose file uses
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ odroid_container_user }}/Containers/jellyfin/tailscale-state/"
    - "/home/{{ odroid_container_user }}/Containers/jellyfin/tailscale-config/"
    - "/home/{{ odroid_container_user }}/Containers/jellyfin/tailscale-config/config/"
    - "/home/{{ odroid_container_user }}/Containers/jellyfin/config/"
    - "/home/{{ odroid_container_user }}/Containers/jellyfin/cache/"
    - "/home/{{ odroid_container_user }}/Containers/jellyfin/media/"

- name: Copy the docker compose file to the server
  ansible.builtin.template:
    src: "jellyfin-docker-compose.yml"
    dest: "/home/{{ odroid_container_user }}/Containers/jellyfin/docker-compose.yml"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

# Make sure this dest file maps to /config/tailscale.json in the container...
# inspect manually if it is the first time placing this file onto your server
- name: Copy the tailscale json file to the server
  ansible.builtin.template:
    src: "tailscale.json"
    dest: "/home/{{ odroid_container_user }}/Containers/jellyfin/tailscale-config/config/tailscale.json"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "/home/{{ odroid_container_user }}/Containers/jellyfin"
    state: present
