---
version: "3.7"
name: jellyfin
services:
  tailscale:
        hostname: jellyfin                         # This will become the tailscale device name
        image: docker.io/tailscale/tailscale:latest
        environment:
          - TS_AUTH_KEY={{ iancleary_tailscale_auth_key }}
          - TS_SERVE_CONFIG=/config/tailscale.json
          - TS_STATE_DIR=/var/lib/tailscale
        volumes:
            - ${PWD}/tailscale-state:/var/lib/tailscale
            - ${PWD}/tailscale-config/config:/config       # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
        cap_add:                                    # Required for tailscale to work
          - net_admin
          - sys_module
        restart: unless-stopped

  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: service:tailscale
    depends_on:
      - tailscale
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/cache:/cache
      - ${PWD}/media:/media
    restart: unless-stopped

volumes:
  jellyfin:
    driver: local
  tailscale:
    driver: local
