---
- name: Pull tailscale image
  community.docker.docker_image:
    name: docker.io/tailscale/tailscale
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Pull s-pdf image
  community.docker.docker_image:
    name: docker.io/frooodle/s-pdf
    source: pull
    tag: latest
    force_source: true
    # Select platform for pulling. If not specified, will pull whatever docker prefers.

- name: Create the directories that the compose file uses
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/{{ data_pool }}/s-pdf/tailscale-state/"
    - "/{{ data_pool }}/s-pdf/tailscale-config/"
    - "/{{ data_pool }}/s-pdf/tailscale-config/config/"
    - "/{{ data_pool }}/s-pdf/trainingData/"
    - "/{{ data_pool }}/s-pdf/extraConfigs/"

- name: Copy the docker compose file to the server
  ansible.builtin.template:
    src: "s-pdf-docker-compose.yml"
    dest: "/{{ data_pool }}/s-pdf/docker-compose.yml"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

# Make sure this dest file maps to /config/tailscale.json in the container...
# inspect manually if it is the first time placing this file onto your server
- name: Copy the tailscale json file to the server
  ansible.builtin.template:
    src: "tailscale.json"
    dest: "/{{ data_pool }}/s-pdf/tailscale-config/config/tailscale.json"
    owner: "{{ odroid_container_user }}"
    group: "{{ odroid_container_user_group }}"
    mode: "0644"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "/{{ data_pool }}/s-pdf"
    state: present
